name: Generate Screenshots

on:
  pull_request:
  push:
    tags:
      - "v*"

jobs:
  screenshot:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.7 <3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        shell: powershell

      - name: Increase resolution
        run: |
          Set-DisplayResolution -Width 1920 -Height 1080 -Force
        shell: powershell

      - name: Run app and take screenshot
        run: |
          # Start app and take screenshot
          python screenshot.py
        shell: powershell

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-light
          path: screenshot-light.png
